### ISSUE TITLE
Try and doc teoBase with TEO_push demo

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-main#11]
_From @jgvictores on October 14, 2016 8:31_

Try and doc teoBase with [TEO_push](https://github.com/roboticslab-uc3m/TEO_push) demo.
- [ ] Try
- [ ] Doc at http://robots.uc3m.es/index.php/Procedimiento_Demos

_Copied from original issue: roboticslab-uc3m/kinematics-dynamics#65_

**Comment by jgvictores** [comment]
https://github.com/roboticslab-uc3m/TEO_push/issues/2

**Comment by jgvictores** [comment]
Originally set for OCT 10. :smile:

**Comment by PeterBowman** [comment]
Please create a separate demo-specific .xml file in the https://github.com/roboticslab-uc3m/TEO_push repo.
