### ISSUE TITLE
Try and doc teoBase with walking demo

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-main#12]
_From @jgvictores on October 14, 2016 8:55_

Try and doc teoBase with walking demo.
- [ ] Try
- [ ] Doc at http://robots.uc3m.es/index.php/Procedimiento_Demos

_Copied from original issue: roboticslab-uc3m/kinematics-dynamics#67_

**Comment by jgvictores** [comment]
Requires https://github.com/roboticslab-uc3m/teo-main/issues/53 first.

**Comment by jgvictores** [comment]
Originally set for NOV 01. :smile:

**Comment by jgvictores** [comment]
_From @PeterBowman on May 3, 2017 16:52_

Blocked by #53.

**Comment by PeterBowman** [comment]
Fixing broken ref in my previous comment: blocked by roboticslab-uc3m/kinematics-dynamics#53.

**Comment by PeterBowman** [comment]
I believe teoBase.xml is not intended for specific demos, but rather for launching main controllers. Demo-related launchers should be hosted in their own XML. Anyway, there is no such thing as a "walking demo" as far as I know, besides the approach taken at https://github.com/roboticslab-uc3m/teo-main/issues/51.
