### ISSUE TITLE
How to do a grasping hand for Teo

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-main#19]
_From @jgvictores on October 4, 2017 15:26_

_From @rsantos88 on October 4, 2017 8:33_

To advance in the correct way with [grasping in openrave](http://openrave.org/docs/0.6.6/openravepy/databases.grasping/), we need to make the actual Teo hand able to open and close like the [barrett hand](https://github.com/rdiankov/openrave/blob/master/src/robots/barretthand.kinbody.xml).
Which are the steps to follow?

_Copied from original issue: roboticslab-uc3m/openrave-yarp-plugins#37_

_Copied from original issue: roboticslab-uc3m/questions-and-answers#31_

**Comment by jgvictores** [comment]
_From @rsantos88 on October 4, 2017 8:55_

First, I think we need to separate the fingers in three different 3D files..

![hand](https://user-images.githubusercontent.com/15872457/31167472-7906b6e0-a8f2-11e7-9f2d-3b8d6c9f8b5e.jpg)

or.. maybe 6 files? (2 parts per finger..?)

**Comment by jgvictores** [comment]
Blocked by: https://github.com/roboticslab-uc3m/teo-openrave-models/issues/9

**Comment by rsantos88** [comment]
A grasping hand was added to the robot

**Comment by jgvictores** [comment]
Old issue closed, now blocked by https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/86

**Comment by jgvictores** [comment]
Closed https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/86, now working on https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/97

**Comment by PeterBowman** [comment]
The referenced issues have been closed, and now we also have a fully actuated gripper in the Gazebo models thanks to https://github.com/roboticslab-uc3m/teo-gazebo-models/pull/4. @jgvictores what are the next steps?

**Comment by jgvictores** [comment]
Original author was not me, I'm just mentioned due to the old issue move mechanism.

I'd close! :)

**Comment by jgvictores** [comment]
ps: oh yes, we did all this. closing!
