### ISSUE TITLE
Changes of forearm and its consequences

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-main#23]
Respect with the last changes of [forearm piece](https://github.com/roboticslab-uc3m/teo-developer-manual/pull/20), it remains to make all the changes regarding the new kinematics, diagrams, model of Teo, etc ...

**Comment by jgvictores** [comment]
Okay, please remember the current [workflow-for-assets in teo-software-manual/](https://github.com/roboticslab-uc3m/teo-software-manual/tree/e88693d314a04309cfbacc09b9bb6636b176e4b4#workflow-for-assets).

**Comment by jgvictores** [comment]
Blocks #38 among others.

**Comment by jgvictores** [comment]
@rsantos88 This affects https://github.com/roboticslab-uc3m/teo-main/issues/38

Are the current values at https://github.com/roboticslab-uc3m/teo-developer-manual/blob/cabf02d5438e2735a4983b82f9ff0c6fca2fe6cd/csv/lengths.csv correct (via diagram at https://github.com/roboticslab-uc3m/teo-developer-manual/blob/cabf02d5438e2735a4983b82f9ff0c6fca2fe6cd/fig/Lengths.png)?

**Comment by rsantos88** [comment]
updated via https://github.com/roboticslab-uc3m/teo-developer-manual/pull/58

**Comment by rsantos88** [comment]
also updated kinematic files via https://github.com/roboticslab-uc3m/teo-configuration-files/pull/22

**Comment by jgvictores** [comment]
Done by @rsantos88 via:
- https://github.com/roboticslab-uc3m/teo-developer-manual/pull/58
- https://github.com/roboticslab-uc3m/teo-configuration-files/pull/22
