### ISSUE TITLE
Missing TEO's Right Leg Board

### ISSUE THREAD

**Issue by AlvaroMartinezR** [roboticslab-uc3m/teo-main#29]
@rsantos88 and me are trying to unify the limits of TEO's joint based on the real robot rather than broad approximations, but without the encoder board we can't. As mentioned in https://github.com/roboticslab-uc3m/teo-main/issues/15

![img_20180119_111449](https://user-images.githubusercontent.com/26522251/35146059-304243c2-fd0a-11e7-8298-72363449317c.jpg)

**Comment by rsantos88** [comment]
@AlvaroMartinezR drivers board , more exactly :joy:

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#1
