### ISSUE TITLE
Migration from Debian 6.0 to Ubuntu 14.04 on TEO

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-main#32]
Migration from Debian 6.0 to Ubuntu 14.04 on TEO

ToDo: 
- [x] Try hc-driver-4.9 on TEO https://github.com/roboticslab-uc3m/teo-main/issues/26
- [x]  jr3 drivers with Ubuntu 14.04
- [x] Try xsense (see https://github.com/roboticslab-uc3m/installation-guides/issues/35 )
- [x] Install daemontools as described [here](https://github.com/roboticslab-uc3m/teo-software-manual/blob/master/appendix/b-teo-network-information.md)
- [x] Change boot order: make Ubuntu default.
- Documentation
   - [x] Create GitHub releases, before erasing all Debian 6.0 documentation.
   - [x]  update [this](https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/doc/yarp-devices-install.md#os-requirements) table using the agreed format (csv) -> Update: [here](https://github.com/roboticslab-uc3m/yarp-devices/blob/ffce5d9918cf5b8c6a81a2dea1d447edde772b15/doc/os-requirements.csv)

**Comment by jgvictores** [comment]
> jr3 drivers with Ubuntu 14.04

Blocked by https://github.com/roboticslab-uc3m/LoliRepo/issues/1

**Comment by jgvictores** [comment]
Jr3 on Ubuntu still has issues... On Debian `lsmod` we have:
```
jr3pci_driver          23698  0 
jr3_pci                 6086  0 
comedi                 24352  1 jr3_pci
```

**Comment by jgvictores** [comment]
JR3 working via https://github.com/roboticslab-uc3m/jr3pci-linux/commit/3cb1a29cf3782b3d3808d3e8f9c2d65a91499879 (current `develop` of https://github.com/roboticslab-uc3m/jr3pci-linux )!!

**Comment by jgvictores** [comment]
- No longer blocked by https://github.com/roboticslab-uc3m/LoliRepo/issues/1.
- WIP at https://github.com/roboticslab-uc3m/installation-guides/issues/35

**Comment by jgvictores** [comment]
- https://github.com/roboticslab-uc3m/installation-guides/issues/35 closed.

**Comment by jgvictores** [comment]
- JR3 working on Ubuntu 14.04 and documented at https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-jr3.md
- XSENS working on Ubuntu 14.04 and documented at https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-xsens.md

**Comment by jgvictores** [comment]
Updated links to these docs on https://github.com/roboticslab-uc3m/teo-software-manual/blob/fb1c7b73235bfacab411b4fe9d344b2be2d0c4e5/appendix/b-teo-network-information.md

**Comment by jgvictores** [comment]
> Install daemontools as described here
```
The YARP_CONF variable is deprecated and it is no longer used. Please check the documentation for yarp::os::ResourceFinder::getConfigHome() warning: YARP name server(s) not configured, ports will be anonymous warning: check your namespace and settings with 'yarp detect'
```

**Comment by rsantos88** [comment]
From [here](https://github.com/robotology/yarp/blob/9712fdec65a676247d9a297928ff5f4ad8286901/src/libYARP_OS/src/NameConfig.cpp#L80-L94) we see `YARP_CONF` is deprecated, and from the called `ResourceFinder::getConfigHome()`, and from [its documentation](https://github.com/robotology/yarp/blob/9a395f6e41e01d8d350b6a4e5e2b2f6c6f913b74/src/libYARP_OS/include/yarp/os/ResourceFinder.h#L359-L376) we can see that `YARP_CONFIG_HOME` is now used instead.

Tested and working! :tada::tada::tada:

**Comment by rsantos88** [comment]
Starting documentation!
Shoud create GitHub releases, before erasing all Debian 6.0 documentation, at least on https://github.com/roboticslab-uc3m/yarp-devices

**Comment by jgvictores** [comment]
Created https://github.com/roboticslab-uc3m/yarp-devices/releases/tag/old-debian-6.0

**Comment by jgvictores** [comment]
Created https://github.com/roboticslab-uc3m/installation-guides/releases/tag/old-debian-6.0

**Comment by rsantos88** [comment]
>  update [this](https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/doc/yarp-devices-install.md#os-requirements) table using the agreed format (csv)

Here it is: https://github.com/roboticslab-uc3m/teo-main/blob/issue%2332/doc/os-requirements.csv

**Comment by rsantos88** [comment]
pull request:  #34

**Comment by rsantos88** [comment]
Do you want to convert [this](https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/doc/yarp-devices-install.md#specific-dependencies) table to .cvs too, don't you?

**Comment by jgvictores** [comment]
In fact most work done at https://github.com/David-Estevez/yarp-devices/tree/fix-161-migrate-tables, check issue https://github.com/roboticslab-uc3m/yarp-devices/issues/161.
The basic idea is to conclude https://github.com/roboticslab-uc3m/yarp-devices/issues/161 but taking into account that all Debian 6.0 information can be removed.

**Comment by jgvictores** [comment]
Also careful with https://github.com/roboticslab-uc3m/yarp-devices/commit/98ec0efa63423406cb94fe49b76eaee01d4e8995 (fix-165-find-phidget)

**Comment by jgvictores** [comment]
Added "Change boot order: make Ubuntu default." to description.

**Comment by rsantos88** [comment]
> Added "Change boot order: make Ubuntu default." to description.

Done in both computers. Now you can see the next screen when grub starts, ease to recognize:
(Default time to choose: 5s)

![20180208_155012](https://user-images.githubusercontent.com/15872457/35979186-fed421c8-0ce7-11e8-8878-befa2b8baed7.jpg)

**Comment by jgvictores** [comment]
> Do you want to convert this table to .csv too, don't you?

Great. Basically missing merge of the branches that involve this file.

**Comment by jgvictores** [comment]
Finished documentation, which was final step, at ffce5d9918cf5b8c6a81a2dea1d447edde772b15.
