### ISSUE TITLE
Add travis continuous integration

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-main#8]
Add continuous integration (e.g. via travis).

**Comment by PeterBowman** [comment]
Once we have a functional Travis YAML file, I'd like to propose enabling [scheduled cron jobs](https://docs.travis-ci.com/user/cron-jobs/) to make this repo aware of changes in dependent (YCM-loaded) repositories.

**Comment by jgvictores** [comment]
> Once we have a functional Travis YAML file, I'd like to propose enabling scheduled cron jobs to make this repo aware of changes in dependent (YCM-loaded) repositories.

I agree, that makes sense in this kind of super-build/meta-package repo. Good idea! :smile:

**Comment by jgvictores** [comment]
Build passing at 03d4ac78c7b7a40ec36192bd4a3be7c897d3ab27.

**Comment by jgvictores** [comment]
Have activated daily build on `master` via: https://travis-ci.org/roboticslab-uc3m/teo-main/settings

Closing issue!
